- hosts: web
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Start Apache
    systemd:
      state: started
      enabled: yes
      name: httpd
  
  - name: Install Unzip
    yum:
      name: unzip
      state: latest

  - name: Unarchive Template
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page1/photoprowess.zip
      dest: /tmp/
      remote_src: yes

  - name: Copy Template to /var/www/html
    copy:
      src: /tmp/photoprowess/index.html
      dest: /var/www/html/
      remote_src: yes
      
  - name: Restart Apache
    service:
      name: httpd
      state: restarted
