- hosts: all
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Start service httpd, if not started
    systemd:
      state: started
      enabled: yes
      name: httpd
  
  - name: Install Unzip
    yum:
      name: unzip
      state: latest

  - name: Download and extract Template
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page286/creative-studio.zip
      dest: /tmp/
      remote_src: yes

  - name: Copy Template to /var/www/html
    copy:
      src: /tmp/creative-studio/public_html/
      dest: /var/www/html/
      remote_src: yes
      
  - name: Restart Apache
    service:
      name: httpd
      state: restarted
